version: '3.8'

services:
  catalogdb:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: CatalogDb
    restart: always
    ports:
      - "5434:5432"
    volumes:
      - postgres_catalog:/var/lib/postgresql/data

  catalog.api:
    build:
      context: .
      dockerfile: Services/Catalog/Catalog.API/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_HTTP_PORTS: 8080
      #ASPNETCORE_HTTPS_PORTS: 8081
      ConnectionStrings__Database: "Server=catalogdb;Port=5432;Database=CatalogDb;User Id=postgres;Password=postgres"
    depends_on:
      - catalogdb
    ports:
      - "6000:8080"
      #- "6060:8081"
    #volumes:
      #- /Users/bugra/.aspnet/dev-certs/https:/https

volumes:
  postgres_catalog:
